### ISSUE TITLE
Password stored warning

### ISSUE THREAD

**Issue by naugtur** [VaultVulp/gp-docker-action#3]
I'm getting this warning when running the action:
```
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
WARNING! Your password will be stored unencrypted in /github/home/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
```

Is that expected?

**Comment by VaultVulp** [comment]
Thanks for your question, @naugtur!

Answering it, yes - this is expected behavior. 

This is the line, that raises this warning:
```bash 
docker login -u publisher -p ${DOCKER_TOKEN} docker.pkg.github.com
```
We have to pass our authentication token into the `docker login` command, to be able to publish Docker images. This password is a temporary one, that is generated by GitHub itself specifically for this concrete Actions run, so, as far as I know, there should be no security issues.

And you can take a look at this repo's code to make sure, that I do not store your password.

**Comment by naugtur** [comment]
I'm definitely not worried you're storing it. Just letting you know there's a new option according to the warning. It'd probably work the same but without the warning.

**Comment by VaultVulp** [comment]
Got it. I understand your concern about this warning, and I do not like to see it too. 

The solution you are referring to requires the installation of a third-party tool known as `pass` that isn't integrated into OS and isn't developed by the Docker team. It will complicate this action and may create other security issues.

I have to says, that I'm constantly looking into resolving this warning, due to the fact, that I've to run my docker `login/build/push` pipelines in different environments. But right now we have to accept this problem and wait till the Docker team provides us with the solution.

**Comment by naugtur** [comment]
Makes sense. You could document how this warning is irrelevant in the docs, I'd look for a different github action if I wasn't in a rush, so your adoption might be hurting.
Thanks for your attention! I appreciate it.

**Comment by VaultVulp** [comment]
Thanks for your suggestion, @naugtur. I'll try to update docs to make it clear, that this problem is a well known.
